apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "kiali.csyeteam03.xyz"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001  # Default port for Kiali

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "prometheus.csyeteam03.xyz"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: prometheus.istio-system.svc.cluster.local
        port:
          number: 9090  # Default port for Prometheus

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "grafana.csyeteam03.xyz"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000  # Default port for Grafana

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "jaeger.csyeteam03.xyz"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: jaeger-query.istio-system.svc.cluster.local
        port:
          number: 5775  # Default port for Jaeger Query UI

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: loki-virtualservice
  namespace: istio-system
spec:
  hosts:
  - "loki.csyeteam03.xyz"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: loki.istio-system.svc.cluster.local
        port:
          number: 3100  # Default port for Loki
