variable "environment" {}
variable "project_id" {}
variable "region" {}
variable "gke_subnet_name" {}
variable "network_name" {}
variable "machine_type" {}
variable "disk_type" {}
variable "pod_ranges" {}
variable "service_ranges" {}
variable "gke_subnet_ip" {}
variable "public_subnet_ip" {}
variable "kubernetes_version" {}
variable "node_version" {}