variable "environment" {}
variable "project_id" {}
variable "region" {}
variable "gke_subnet_name" {}
variable "network_name" {}
variable "machine_type" {}
variable "disk_type" {}
variable "pod_ranges" {}
variable "service_ranges" {}
variable "gke_subnet_ip" {}
variable "public_subnet_ip" {}
variable "local_ip" {}
variable "local_ip_s" {}
variable "kubernetes_version" {}
variable "node_version" {}
variable "api_server_namespace" {}
variable "api_server_ksa_name" {}
variable "db_operator_namespace" {}
variable "db_operator_ksa_name" {}
variable "gke_crypto_key_id" {}
variable "sops_crypto_key_id" {}
variable "compute_sa_email" {}
variable "bastion_sa_email" {}
variable "cluster_name" {}
